### ISSUE TITLE
Can't find node

### ISSUE THREAD

**Issue by seanhess** [DefinitelyTyped/tsd#1]
I installed. Then `tsd all` spits out

```
typescript> tsd all
env: node\r: No such file or directory
```

My node install works fine, and `env node` works as well.

**Comment by vasanthB5** [comment]
Hi could anyone help me...I am not able to run the command tsd at all......it is thrwoing me an error command not found I am working on Macbook..ubuntu..please help me..I was able to download node and npm checked everything working fine...npm install tsd -g --> throws me npm ERR code EACCES.......of about 15 lines.. please help me

**Comment by Diullei** [comment]
Hi @vasanthB5 

You have this error trying install tsd, right?

if running:

```
npm install tsd -g
```

you have the EACCES error, this is because you need to use "sudo":

```
sudo npm install tsd -g
```

Could you try it?

**Comment by vasanthB5** [comment]
oh thank you bro...............worked

**Comment by Diullei** [comment]
:+1:

**Comment by vasanthB5** [comment]
Bro I am very much interested in this Angular..Can you tell me how to run this by Node.js.. I am facing issues in by using node..some syntax issues..Do you have any thing to just run my app in node.js..help needed

**Comment by Diullei** [comment]
@vasanthB5 Take a look at https://github.com/angular/angular/issues repo ;)
