### ISSUE TITLE
Package linker's folder scan uses hardcoded folders

### ISSUE THREAD

**Issue by rraziel** [DefinitelyTyped/tsd#109]
Hello,

The new `tsd link` command (which sounds rather nice by the way) seems to scan installed dependencies looking for package.json and bower.json files. My issue with this is that my project's .bowerrc defines a directory:

```
{
  "directory": "library"
}
```

I know this is not a common situtation, but with the currently hard-coded folders I have to create a symlink just to be able to run the link command...

**Comment by schmkr** [comment]
:+1:  +1
