### ISSUE TITLE
Remove dependency to jQuery from angular

### ISSUE THREAD

**Issue by awerlang** [DefinitelyTyped/tsd#118]
In the first lines of angular.d.ts there's this line:

```
/// <reference path="../jquery/jquery.d.ts" />
```

jQuery is optional for angular to work, and many run without it, because you might not need it.

IfI remove its typing file, I got

```
Error	24	Incorrect reference: file "...\typings\jquery\jquery.d.ts" does not exist
```

Would it be possible to make it optional also in its typing?

PS: also, there's the already noticed conflict with protractor, that defines a '$' symbol.

**Comment by Bartvds** [comment]
This is a known issue but the definition files are hosted by the DefinitelyTyped repository.

Please discuss here https://github.com/borisyankov/DefinitelyTyped/issues

I'll close this as this is not solvable by TSD.
