### ISSUE TITLE
How can I contribute to tsd development?

### ISSUE THREAD

**Issue by joshuacc** [DefinitelyTyped/tsd#136]
I'd love to help improve tsd and get 0.6.0 stable released. Unfortunately, based on looking at the most recent commits, it appears that development has stalled for a while. Is there anything I can do to help out?

Happy to triage bug reports/pull requests, or anything else that is helpful.

Thanks!

**Comment by blakeembrey** [comment]
Hi @joshuacc, thanks for asking! I'm going to be jumping into development soon and start bringing the project back up to date. If there's anything, I'll definitely let know. Once I start committing and creating issues and finally PRs, another set eyes is helpful :smile:
