### ISSUE TITLE
DefinitelyTyped for salesforce REST api

### ISSUE THREAD

**Issue by yogeshksraj** [DefinitelyTyped/tsd#141]
in DefinitelyTyped-master there are so many definition available but i want to create hybrid app for mobile using SalesForce for that we need force.d.ts

**Comment by blakeembrey** [comment]
Hi @yogeshksraj! I'm not sure whether you're in the right place. This is the repo for the tool, TSD, not for general definition support. I'd have a look at the TypeScript handbook to get started writing your own definitions, as well as the definitions on https://github.com/borisyankov/DefinitelyTyped for examples, and post any questions to StackOverflow or somewhere similar where people will be equipped to answer you.
