### ISSUE TITLE
IAB MRAID support 

### ISSUE THREAD

**Issue by BirdTho** [DefinitelyTyped/tsd#148]
I am interested in writing a Typescript library for MRAID 1.0/2.0 outlined by the IAB standards at http://www.iab.net/mraid
There are several PDFs present and I have experience working with the API. Still autocomplete for it would be nice.

How do I go about this? I'm not accustomed to contributing to open sauce.

**Comment by blakeembrey** [comment]
Hi @BirdTho. I think you're posting in the wrong location. This is for issues with the tool, TSD, not for general support on writing definitions. Maybe you can try StackOverflow or somewhere similar. Also, check out the TypeScript handbook and other examples for writing your own definitions.

Also, I just wanted to let you know that it's called open source, source as in "source code" and not "apple sauce".
