### ISSUE TITLE
Is TSD dead?

### ISSUE THREAD

**Issue by mr-moon** [DefinitelyTyped/tsd#149]
Just checked that there was no commit activity during last 6 months. Does this mean that TSD is not maintained any more? Could you please tell us what is the future?

**Comment by blakeembrey** [comment]
Hi @mr-moon, I can't comment on what happened to @Bartvds but I'm going to tell you it most definitely is not dead. I'm about to jump into the project and I'm starting to review all the issues to formulate a basic proposal for the next version of TSD that I'd like everyone to contribute to. Expect that some time today or tomorrow, and I'm going to start working on it this weekend. Thanks for checking in though.

**Comment by vvakame** [comment]
I'm making yet another tsd. https://www.npmjs.com/package/dtsm
please check it.
