### ISSUE TITLE
tsd reinstall does not remove stale typings

### ISSUE THREAD

**Issue by alexeagle** [DefinitelyTyped/tsd#151]
I updated my tsd.json to remove touch-events.d.ts, because the new typescript 1.5 beta includes those natively in the lib.d.ts, and the compilation fails due to duplicate type definitions.

I run tsd reinstall, and the touch-events.d.ts is left in the typings folder. Based on the documentation for reinstall:
```Reset the definitions to the commits listed in tsd.json```
I would expect any typings not in tsd.json to be removed.

The current workaround is everyone on the team needs to remove the typings folder whenever something is removed from tsd.json.

**Comment by blakeembrey** [comment]
@alexeagle You're right, I'd expect this too. I plan on doing a lot of refactoring on this project and that's one of the first things being fixed in #150. Thanks for the report :+1:

**Comment by alexeagle** [comment]
Nice, I noticed your roadmap this morning, and glad to see you are laying plans for those fixes. Soon we will figure out the right way to distribute the type definitions for Angular, likely with tsd.

**Comment by Diullei** [comment]
I think this should be resolved by adding an `uninstall` command. With this I'll ensure that any of my own typing (if exists) in the same directory (`typings`) will not be removed.

What do you think?

**Comment by alexeagle** [comment]
I don't think that solves our problem: we check in a tsd.json as a means to
keep the typings directories on the machines of all our team members in
sync. What command would we put in 'npm install' that would cause all the
typings to be synced? `tsd uninstall --all && tsd reinstall`?

**Comment by Diullei** [comment]
Ok @alexeagle, I Got your point. In this case the reinstall command must remove the typings not referenced by tsd.json

**Comment by jimlloyd** [comment]
@alexeagle see the discussion in #179. Would do you think of `tsd reinstall --clean` as a solution for your problem?

**Comment by alexeagle** [comment]
@jimlloyd thanks for the notification, I commented over there.

**Comment by Diullei** [comment]
Hi @alexeagle! I published a new version (`tsd@0.6.5-beta`) to fix the bug that you reported here https://github.com/DefinitelyTyped/tsd/issues/184#issuecomment-136424203

Could you verify if it is ok now?

To install:

```
npm install tsd@0.6.5-beta
```

**Comment by alexeagle** [comment]
yes, it looks good now, I sent a PR to use it in Angular:
https://github.com/angular/angular/pull/3940

Thanks!

**Comment by Diullei** [comment]
Nice! I'm glad to help you with this issue! 

I'll close this issue for now, feel free to reopen it if you got another problem.

Thanks!
