### ISSUE TITLE
angular-resource.d.ts - IResourceClass'T missing $promise and $resolved properties.

### ISSUE THREAD

**Issue by rcollette** [DefinitelyTyped/tsd#152]
An IResourceClass<T> actually has both $promise and $resolved properties.

I am currently having to cast objects of this type to <any> to be able to access these properties.

IResourceClass<T> is returned by IResourceService

**Comment by blakeembrey** [comment]
@rcollette I think you've got the wrong repo. Please log definition issues at https://github.com/borisyankov/DefinitelyTyped
