### ISSUE TITLE
Can't "npm shinkwrap" because of extraneous deps

### ISSUE THREAD

**Issue by zckrs** [DefinitelyTyped/tsd#156]
`npm ERR! extraneous: minichain@0.0.1 /Users/mdara/github/gulpAngular/node_modules/tsd/node_modules/minichain`

With `npm prune` => `unbuild minichain@0.0.1`

Something is wrong in your `package.json` or in your `package.json` of deps.  (minifamily)

**Comment by blakeembrey** [comment]
Hi @zckrs! Could I ask which version of TSD you're using?

**Comment by zckrs** [comment]
Thank you for reply

I used `"tsd": "~0.6.0-beta.5"`

**Comment by mikesigs** [comment]
I am also having this problem with tsd@0.6.0

**Comment by tensorproduct** [comment]
I'm seeing this problem too. The fix from basarat works to resolve it. Thanks!

**Comment by Diullei** [comment]
Fixed here https://github.com/DefinitelyTyped/tsd/pull/159. Release [0.6.1](https://github.com/DefinitelyTyped/tsd/releases/tag/0.6.1)
