### ISSUE TITLE
moment.js doesn't pull new moment-node.d.ts required/referenced file

### ISSUE THREAD

**Issue by Gitgiddy** [DefinitelyTyped/tsd#158]
moment.d.ts content is now:

    // Type definitions for Moment.js 2.8.0
    // Project: https://github.com/timrwood/moment
    // Definitions by: Michael Lakerveld <https://github.com/Lakerfield>, Aaron King  <https://github.com/kingdango>, Hiroki Horiuchi <https://github.com/horiuchi>, Dick van den Brink <https://github.com/DickvdBrink>, Adi Dahiya <https://github.com/adidahiya>
    // Definitions: https://github.com/borisyankov/DefinitelyTyped

    /// <reference path="moment-node.d.ts" />

    declare var moment: moment.MomentStatic;

but the tsd package(?) doesn't include it.  It isn't clear where this should be added or "whose responsibility" it is to fix.

**Comment by Diullei** [comment]
Hi @Gitgiddy, do you have a `tsd.json` file on your root directory? Could you check the `commit` key value? it must to be the latest DefinitelyTyped  commit (`484544d14d400190b20f270341c97b16adc0f1ef` until this moment)

My file looks like this:

```json
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "moment/moment.d.ts": {
      "commit": "484544d14d400190b20f270341c97b16adc0f1ef"
    }
  }
}
```

**Comment by Gitgiddy** [comment]
Yes, that number is the same.

**Comment by Diullei** [comment]
please, use the following command:

`tsd update --save --overwrite`

**Comment by Gitgiddy** [comment]
I did do that earlier with no effect, I also force reinstalled with tsd.  

I have since manually copied the file so the test is maybe soured with that now.

If you looked into it and it's not a real issues, then perhaps it's an old version of tsd on my side or something.  Thanks.

**Comment by Diullei** [comment]
Ok, `tsd update -so` worked fine to me. I'm using the `0.6.0` version (on Windows).
