### ISSUE TITLE
TSD behind corporate proxy #71 new issue

### ISSUE THREAD

**Issue by eheb** [DefinitelyTyped/tsd#162]
I start with tsd 0.6.1 on windows. I put my corporate proxy in Utilisateur/xxx/.tsdrc file :+1: 
HTTP_PROXY=http://fr-proxy.groupinfra.com:1234
and now with any tsd command i get :+1: 
Unexpected token H
SyntaxError: Unexpected token H
    at Object.parse (native)
    at parseJson (C:\Users\heberte\AppData\Roaming\npm\node_modules\tsd\build\xm
\fileIO.js:30:21)
...

**Comment by Diullei** [comment]
Hi @eheb, this file must be in json format. Try with this:

> Utilisateur/xxx/.tsdrc
```json
{
	"HTTP_PROXY": "http://fr-proxy.groupinfra.com:1234"
}
```

**Comment by Diullei** [comment]
@eheb please, reopen this issue if you still have a problem. Thank you!

**Comment by eheb** [comment]
Yes, i have done this.Thank you for your beedback. Eric Hébert
 


     Le Mercredi 10 juin 2015 13h46, Diullei Gomes <notifications@github.com> a écrit :
   

 @eheb please, reopen this issue if you still have a problem. Thank you!—

**Comment by Diullei** [comment]
:+1:
