### ISSUE TITLE
When definitely types from repository goes to tsd?

### ISSUE THREAD

**Issue by greybax** [DefinitelyTyped/tsd#171]
I've added definitely types for [Quixote library](https://github.com/greybax/DefinitelyTyped/tree/master/quixote), it appeared in repository after applied my pull request. But I couldn't see it in TSD . How it should be added on TSD ?

**Comment by Diullei** [comment]
Hi @greybax, you can query this typing with tsd:

```
tsd query quixote --info
```

> results
```
 - quixote / quixote    
   >> quixote 0.7.0             : quixote-css.com
    @ Aleksandr Filatov         : github.com/greybax
    < quixote (external module) 
```

The tsd website (http://definitelytyped.org/tsd/) needs to be re-indexed to get this new typing. The last index has been made six days ago. I will make a new today. 

I'm working to improve this indexing and allow this to occur automatically.

you can follow it here https://github.com/DefinitelyTyped/tsd/issues/172

**Comment by greybax** [comment]
Thank you! :)

**Comment by blakeembrey** [comment]
Closing this issue as it looks like it's been resolved. If you have any other issues, feel free to open a new issue :smile:
