### ISSUE TITLE
using tsd on TravisCI throws a HTTP status code 403

### ISSUE THREAD

**Issue by rolandjitsu** [DefinitelyTyped/tsd#175]
I'm using tsd on TravisCI to install some definitions and it seems like I just got a HTTP status code `403` from Git during the tsd install command. You can check the errored [build](https://travis-ci.org/rolandjitsu/ng2-play/builds/67521915) and see more info.

Maybe it's worth mentioning that I am using the API from a node script (`gulpfile.js`) and not in the CLI.

**Comment by blakeembrey** [comment]
@rolandjitsu Are you using the latest version? Have you tried add your key to the environment under `TSD_GITHUB_TOKEN=...` (https://github.com/DefinitelyTyped/tsd#tsdrc under token)?

**Comment by Diullei** [comment]
Same issue related here https://github.com/DefinitelyTyped/tsd/issues/163

Just to complement the @blakeembrey response, the version using `process.env.TSD_GITHUB_TOKEN` are not at npm yet. you will need to use solve it using `.tsdrc` file.

**Comment by blakeembrey** [comment]
> Just to complement the @blakeembrey response, the version using `process.env.TSD_GITHUB_TOKEN` are not at npm yet

Shoot, sorry. We should probably release a patch for it :smile:

**Comment by rolandjitsu** [comment]
@blakeembrey yes, `6.0.1` I think, that's the latest right? I have not tried to add my key to the env though, did not know about it.

**Comment by rolandjitsu** [comment]
@Diullei I think that version is there, I just used that strategy with `TSD_GITHUB_TOKEN` and it seems to have worked.

@blakeembrey shall this issue be closed?

**Comment by blakeembrey** [comment]
I think we can close this once the version with `TSD_GITHUB_TOKEN` is released, likely today. I just shot @Diullei an email with some issues I run into during publish of `0.6.2`.

**Comment by blakeembrey** [comment]
Ok, give it a go with `0.6.3` now :smile:
