### ISSUE TITLE
Lazy.js find(...) interface is incorrect

### ISSUE THREAD

**Issue by efreeti** [DefinitelyTyped/tsd#181]
Says:

        find(predicateFn: TestCallback<T>): Sequence<T>;
 
Should be

        find(predicateFn: TestCallback<T>): T;

**Comment by rodrigovidal** [comment]
You should open this issue here: https://github.com/borisyankov/DefinitelyTyped

This repo contains just the tooling.

**Comment by Diullei** [comment]
@efreeti since this is not a problem with this repository I'll close this issue. @rodrigovidal Thanks.
