### ISSUE TITLE
TSD doesn't remove definitions removed from tsd.json

### ISSUE THREAD

**Issue by zuzusik** [DefinitelyTyped/tsd#185]
Version affected: 0.6.3

Steps to reproduce:
1. Create tsd.json, add some definitions
2. Run `tsd reinstall --save`
3. Remove one of the definitions from tsd.json
4. Run `tsd reinstall --save`

Result - removed library definitions are still in `typings` directory and referenced in `tsd.d.ts`
Expected - removed library `.d.ts` files are deleted and no longer referenced in `tsd.d.ts`

Here we also have inconsistency in behaviour - if definition is added into `tsd.json`, then after `tsd reinstall --save` it is downloaded into `typings` and referenced in `tsd.d.ts`

**Comment by Diullei** [comment]
OK, checking...

**Comment by Diullei** [comment]
Hi!

Now the `reinstall` command will remove your custom typings only if you use the `--clean` flag.

```
tsd reinstall --clean
```

To install the beta version:

```
npm install tsd@0.6.5-beta
```

Thanks for reporting this issue.

for more info https://github.com/DefinitelyTyped/tsd/issues/184

> NOTE: The `--save` flag with `reinstall` command is not needed anymore.
