### ISSUE TITLE
Angular2 alpha version 31 and 32 not in the package manager

### ISSUE THREAD

**Issue by DavidGangel** [DefinitelyTyped/tsd#189]
Hi,

When I query the angular2 package with:
tsd query angular2/angular2 -v "2.0.0-alpha.30"

it works fine.
But both for alpha 31 and 32 it returns:
>> zero results

Can someone please check?

**Comment by blakeembrey** [comment]
I can find 31 without any issues, but 32 isn't in the repo (https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2).

**Comment by DavidGangel** [comment]
Did you try to run the command:
tsd query angular2/angular2 -v "2.0.0-alpha.31"
?

**Comment by blakeembrey** [comment]
Yes, that's exactly what I typed.

```
✗ tsd query angular2/angular2 -v "2.0.0-alpha.31"

 - angular2 / angular2-v2.0.0-alpha.31
```

**Comment by DavidGangel** [comment]
Okay that's strange.
I have:
>> tsd 0.6.3

Are there any commands to kind of "pull" the updates from the package manager that I have to perform to get the latest packages?

**Comment by blakeembrey** [comment]
Not sure what's the best way, but maybe try `tsd purge`? @Diullei?

**Comment by Diullei** [comment]
there's no typing for alpha 32, but 31 works fine.

```
$ tsd query angular2/angular2 -v "2.0.0-alpha.31"

 - angular2 / angular2-v2.0.0-alpha.31   
```

@DavidGangel, try use `tsd purge` as @blakeembrey suggested and try again:

```
tsd query angular2/angular2 -v "2.0.0-alpha.31"
```

**Comment by DavidGangel** [comment]
I don't know what was the problem but now it works finally.
Thank you guys for helping me!
