### ISSUE TITLE
fbsdk issue: FBLoginOptions has "scopes" (and it should be "scope"

### ISSUE THREAD

**Issue by yoav-zibin** [DefinitelyTyped/tsd#191]
I couldn't find the repository that has fbsdk, so I'm reporting it here :)

interface FBLoginOptions{
	auth_type ?: string;
	scopes ?: string; // WRONG: should be "scope"
	return_scopes ?: boolean;
	enable_profile_selector ?: boolean;
	profile_selector_ids ?: string;
}

See:
https://developers.facebook.com/docs/reference/javascript/FB.login/v2.4

scope
string
Comma separated list of extended permissions
return_scopes
boolean

**Comment by blakeembrey** [comment]
@yoav-zibin The repository with all type definitions is https://github.com/borisyankov/DefinitelyTyped. Please open an issue or pull request there.
