### ISSUE TITLE
Disable bundle generation

### ISSUE THREAD

**Issue by giggio** [DefinitelyTyped/tsd#192]
You should be able to do not generate the bundle. We do not use it. I suggest you enable us to set it to false, and then you do not create it, like this:

````json
{
  //other config
  "bundle": false
}
````

**Comment by blakeembrey** [comment]
Why would it make sense to disable? You don't have to use it or reference it.

**Comment by cybrown** [comment]
When we do not use this file, it is some kind of pollution in the project.
Having a cleaner work space is a very important argument in favor of the typescript ecosystem.

**Comment by blakeembrey** [comment]
I'm open to a PR for this, but I won't be implementing it into TSD myself. I don't think it's a valuable feature to add and enabling this may cause issues with future TSD releases. By the same argument, the entire `typings` folder is pollution - which I agree visually, but so is node modules, bower components, config files, `package.json`. You can always have your IDE hide the `typings` directory.
