### ISSUE TITLE
tsd link doesn't support npm scoped packages

### ISSUE THREAD

**Issue by jjrv** [DefinitelyTyped/tsd#194]
When looking for Node.js packages, `tsd link` scans `node_modules/*/packages.json` [(see code)](https://github.com/DefinitelyTyped/tsd/blob/d11586889a6a819657e790f2d49726151b9fb2c0/src/tsd/support/PackageLinker.ts#L57) but the glob should also include `node_modules/@*/*/packages.json` because scoped packages are installed in subfolders named after the scope (always prefixed with @).

~~If I change the glob pattern in the linked code to `var pattern = '{*,@*/*}/' + type.infoJson;` then linking works but repeated linking keeps re-discovering the same packages and appending duplicates to `tsd.d.ts` so other changes are still needed somewhere.~~ Pull request #195 seems to fix the problem.

**Comment by blakeembrey** [comment]
Thanks for the PR. I just merged it and will do a release for you. Since I don't use this feature much yet, you'll have to let me know if you have more issues. Thanks!
