### ISSUE TITLE
Overview question

### ISSUE THREAD

**Issue by jannavarro** [DefinitelyTyped/tsd#197]
I am new to typescript and I started building one in VS2015. I have an existing project in javascript where I have node_modules and I am now converting these javascript to ts. It is not particularly clear with me if DefinitelyTyped is what I will use to access my node_modules in typescript. Is it?

Also I created a tsd.json and tried tsd install react--save but it did not put react in my tsd.json. Once I install the type definitions do I also need to put a reference path (e.g:  /// <reference path="../node_modules/react/react" /> ) to every ts file that needs a node_module?

**Comment by blakeembrey** [comment]
@jannavarro Are you using TypeScript >= 1.5? I would recommend you use `tsconfig.json` and add `tsd.d.ts` to your `files` array so things "just work". Beyond that, `tsd install react --save` should add to `tsd.json` and write it into the `typings` directory for you. Those definitions are installed from the definitelytyped repository. For your own modules, I would recommend you adopt the `typescript.defintion` property in `package.json`. It's a much better approach to maintaining your definition as the centralised location will not scale overall. It's great for modules that don't have built-in definitions, but you can control that yourself by the sounds of it. You can always write your own definitions as well, using plain files. 

Here's an example of a module I wrote: https://github.com/blakeembrey/popsicle/blob/master/tsconfig.json#L11-L30. Future releases will definitely have a better getting started and best practices guide, it can be tricky getting into this. Also, we will work on some blog posts - that's kind of missing right now. I'll close this for now, but please keep asking any questions you have.

**Comment by jannavarro** [comment]
@blakeembrey thank you very much for the explanation. This really helped me.

Yes I am using TS 1.5. I found in typescript's github that VS2015 does not have support for tsconfig.json yet so I switched back to atom.

1.) I just want to ask if I have tsconfig.json do I still need a tsd.json?

2.) I appreciate the example you gave me. There are *.d.ts files are stored in lib. When I do a tsd install I don't see any option to specify a path where it would put the d.ts files. Do you transfer the files to lib folder via a build script?

**Comment by blakeembrey** [comment]
The `.d.ts` files I stored in `lib/typings` were actually definitions I've written myself. The definitions installed by TSD are in `typings` up a folder like normal. I keep them separated, otherwise it'd get messy trying to manage the definitions.
