### ISSUE TITLE
Excluding node_modules from being adding to bundled file

### ISSUE THREAD

**Issue by KJoyner** [DefinitelyTyped/tsd#204]
I am using tslint. This has a d.ts file under node_modules/tslint/lib/tslint.t.ts. When I run tsd install, it finds this file and automatically adds it to typings/tsd.d.ts.

Here is the output of tsd install:

-> running install

>> written 7 files:

    - angular-ui-router/angular-ui-router.d.ts
    - angularjs/angular.d.ts
    - foundation/foundation.d.ts
    - jquery/jquery.d.ts
    - lodash/lodash.d.ts
    - restangular/restangular.d.ts
    - stripe/stripe.d.ts
    - tslint (node)

I do not have tslint specified in my tsd.json. Can I exclude this from being added to my tsd.d.ts file. Because of this, I am failing to compile with typescript.

**Comment by gdi2290** [comment]
:+1:

**Comment by eps90** [comment]
:+1:

**Comment by alainsahli** [comment]
:+1:

**Comment by dsebastien** [comment]
+1

**Comment by myitcv** [comment]
This hit us too using `0.6.4-beta`

**Comment by Diullei** [comment]
Fixed! https://github.com/DefinitelyTyped/tsd/pull/205 I'll publish a new release to npm this weekend. I just need to add some tests.

**Comment by myitcv** [comment]
For now `tslint` `v2.4.4` and `v2.5.0-dev4` have been released to work around this problem by [reverting this commit](https://github.com/palantir/tslint/commit/c510503fcdf87efe60bfba0e0b63e422b4a86f66#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

**Comment by Diullei** [comment]
just published a new version to npm (0.6.4) with the fix. Please, let me know if you have any problems.
