### ISSUE TITLE
tsd reinstall and tsd install should allow for a folder

### ISSUE THREAD

**Issue by johnpapa** [DefinitelyTyped/tsd#212]
if I want to run tsd in sub-directory, I have to cd into it then run it. Is there a flag I am missing that allows tsd to install in a sub-directory? 

If not, I'd love to see this work:

`tsd reinstall -t=src -r -o`

which would then reinstall typings in the src folder. where `-t` is target

**Comment by Diullei** [comment]
You can use `--config` flag or change the typing directory path by editing your `tsd.json` file.

Example using `--config`:

Having the following directory structure:

```
root/
 | - src/
      | - tsd.json
```

From `root` directory you can use:

```
tsd install --config src/tsd.json
```

Example editing `tsd.json` file:

Having the following directory structure:

```
root/
 | - src/
 | - tsd.json
```

Open the `tsd.json` file and edit the `path` and `bundle` attributes:

```
{
...
  "path": "src/typings",
  "bundle": "src/typings/tsd.d.ts",
...
}
```

Note: I fixed a bug with `--config` option. To get the latest version you must install `tsd@0.6.5-beta`

https://github.com/DefinitelyTyped/tsd/releases/tag/0.6.5-beta

**Comment by johnpapa** [comment]
Cool, thanks. I missed this combo `tsd install --config src/tsd.json`. This is better than cd-ing into the folder and back out.

**Comment by Diullei** [comment]
:thumbsup:
