### ISSUE TITLE
link command doesn’t work with --config

### ISSUE THREAD

**Issue by johnpapa** [DefinitelyTyped/tsd#216]
*Proposal*
I'd like to be able to say `tsd link -o src` to have tsd link run and put the output in `src/typings` instead of the root.

*Why?*
I keep my typings and tsconfig.json in a src folder so I can avoid having to use tons of fileGlobs, exclude, files, etc. This way I have no files listed at all in my tsconfig.json and it knows just to use everythign in the `src` folder, including the typings folder.

https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions

**Comment by alexeagle** [comment]
tsd already supports putting the typings folder in a different place:

```
$ mkdir src
$ pushd src
$ npm init
$ npm install es6-promise --save
# creates src/typings
$ popd
$ rm -rf src/typings
$ tsd reinstall --config src/tsd.json
# creates src/typings again
```

the bug is that it doesn't interact with the `link` command:
```
$ npm install angular2
$ tsd link --config src/tsd.json
# creates typings
```

now in this example, I have this mess:
```
$ cat typings/tsd.d.ts
/// <reference path="../node_modules/angular2/bundles/typings/angular2/angular2.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/http.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/router.d.ts" />
$ cat src/typings/tsd.d.ts
/// <reference path="es6-promise/es6-promise.d.ts" />
```

**Comment by johnpapa** [comment]
renamed title

**Comment by Diullei** [comment]
Ok, thanks for reporting this issue. I'll investigate and fix.

**Comment by alexeagle** [comment]
I'm curious, is it intended that the command line flags in tsd should work
for all the commands? Or is it typical that a flag like --config is paired
with the 'install/reinstall' commands in the implementation, and this sort
of inconsistency is common?

**Comment by Diullei** [comment]
Some commands have its specific flags. The `query` command for example has `--history`, `--max`, `--min`, `--info`

I think all commands that interact with `tsd.json` should be sensibilized by `--config` flag.

**Comment by Diullei** [comment]
Hi!

fixed with `0.6.5-beta.2` version! could you test, please? 

```
npm install tsd@0.6.5-beta.2
```

https://github.com/DefinitelyTyped/tsd/releases/tag/0.6.5-beta.2

**Comment by johnpapa** [comment]
I just tested this on OSX and it works. @wardbell tested it on Windows and it works too.

Thanks!

When can we expect this to go live?

**Comment by Diullei** [comment]
Nice! Thanks! I have some test cases to fix, I'll publish a final release this weekend.

**Comment by johnpapa** [comment]
is this close to being published?

**Comment by wardbell** [comment]
We really need this fix soon!

**Comment by johnpapa** [comment]
Is this coming soon? I'm telling folks to install the beta, and that's kinda ugly :)

**Comment by Diullei** [comment]
Hi! Sorry for delay! I'll release it today.

**Comment by johnpapa** [comment]
Thanks. I really link using `link` and being able to put it an a folder of our choice vs using `install`. I prefer the trend of package owners publishing their own `ts` files so its always in sync.

**Comment by wardbell** [comment]
RELIEVED. I've been documenting as if this were ready.  Want to go to press this way.. THANK YOU

**Comment by Diullei** [comment]
just published a new version to npm (0.6.5) with the fix. Please, let me know if you have any problems.

https://github.com/DefinitelyTyped/tsd/releases/tag/0.6.5

**Comment by johnpapa** [comment]
i think we can close this now

**Comment by Diullei** [comment]
Nice, let me know if you have another issues. Thanks :)
