### ISSUE TITLE
connect ECONNREFUSED 

### ISSUE THREAD

**Issue by MortezaT** [DefinitelyTyped/tsd#225]
Hi!

I tried to install definitions via tsd and just in the very first effort I was successful and other tries failed with error : _connect ECONNREFUSED 10.10.34.36:443_

I'm not Using any proxy and the port shown is for Iran National filtering system. I think somehow they think tsd is an intruder to their foolish greatness and really hazardous for Iran politic.

I checked this in different OSes (Ubuntu 15.04 and Windows 7 64 bit)

In Windows I used Psiphon proxy and it just accepted the proxy when port is not set in .tsdrc ("proxy": "127.0.0.1") and when port is set to others (e.g: 8080) this error was shown:

```
    [ERR!] Error: tunneling socket could not be established, cause=getaddrinfo ENOTF
```

OUND 8080 8080:80

**Comment by morajabi** [comment]
I think you can close this one :)
