### ISSUE TITLE
Commit Property????

### ISSUE THREAD

**Issue by gravidThoughts** [DefinitelyTyped/tsd#226]
Here is my `installed` property definition in `tsd.json`.

```
{
    ...
    "installed": {
        "jasmine/jasmine.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        },
        "toastr/toastr.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        },
        "jquery/jquery.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        },
        "requirejs/require.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        },
        "bootstrap/bootstrap.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        },
        "angularjs/angular.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        },
        "angularjs/angular-route.d.ts": {
            "commit": "ebc69904eb78f94030d5d517b42db20867f679c0"
        }
    }
}
```

Notice how all of the commits have the same value. Can someone explain why this is the case?

**Comment by blakeembrey** [comment]
The commit hash the commit at which you've installed the dependency so it can reinstall from the same commit. Every file exists at that commit hash, there's no need to try and find the latest for each file.

**Comment by gravidThoughts** [comment]
@blakeembrey Is this commit hash internal to tsd? Is it data that resides in the definitely typed repositories?

**Comment by blakeembrey** [comment]
Nothing to do with TSD, it's installing from https://github.com/borisyankov/DefinitelyTyped.

**Comment by gravidThoughts** [comment]
@blakeembrey OK so I see that it is the commit hash refers to the latest commit for the entire DefinitelyTyped repository. This latest commit hash looks like it changes multiple times a day.

If I run the `gulp-tsd` task with `latest` set to true, it will update every installed d.ts  in the `tsd.json` to use the latest commit hash.

I am confused, because I would expect the commit hash to represent the latest commit for a specific d.ts.

For example, c71628e0765eb8e240d8eabd2225f64ea2e2fdb8 is the latest commit for angular-route-1.2.d.ts file located at https://github.com/borisyankov/DefinitelyTyped/tree/master/angularjs/legacy.

I guess I will have to just look at tsd source code, because there i no good explanation of the semantics here.

**Comment by gravidThoughts** [comment]
@blakeembrey Hope I am not being a pain :).

I just dove into tsd-cache to see if I could figure out some things.

There are 2 top level folders in the cache. `git-raw-fmt1.0` and `git-api-v3.0.0-fmt1.0`

Using a single example, I selected two files. `f9593d18a57471d7598c283fc26a68463a89b2bc.json` and `f9593d18a57471d7598c283fc26a68463a89b2bc.raw`

Opening up the `.raw` file, it is the content for the d.ts file for requireJS 2.1.8.

Opening up the `.json` file it contains the following.
```
{
  "url": "https://raw.githubusercontent.com/borisyankov/DefinitelyTyped/ebc69904eb78f94030d5d517b42db20867f679c0/requirejs/require.d.ts",
  "key": "f9593d18a57471d7598c283fc26a68463a89b2bc",
  "contentType": "text/plain; charset=utf-8",
  "cacheCreated": "2015-10-06T16:46:58.886Z",
  "cacheUpdated": "2015-10-06T16:46:58.886Z",
  "httpETag": "\"5ca4b476a7b7e4be59333e92639326a004fe19a9\"",
  "httpModified": "2015-10-06T16:46:58.886Z",
  "contentChecksum": "542f42739b38e74752ee37ebed9162352263a02d"
}
```

I am interested in two things. `ebc69904eb78f94030d5d517b42db20867f679c0` in the url property and `f9593d18a57471d7598c283fc26a68463a89b2bc`. What data does this represent in the DefinitelyTyped repository?

I inspected requirejs history and could not find either of those values as commit sha.

**Comment by blakeembrey** [comment]
Not at all. The simplest explanation is to realize that this is just git, so files exist at all commits - even if they didn't change at that commit. That's why, although the file didn't change at that particular commit, it exists at that commit and we can download it using the hash at the same version. Does that help a little? Basically, there's no need to resolve it to the latest commit of that particular file - it will be the same as the last overall commit.

**Comment by gravidThoughts** [comment]
@blakeembrey Yes, it does help. Thanks!
