### ISSUE TITLE
Error: connect ETIMEDOUT 204.13.251.16:443

### ISSUE THREAD

**Issue by wjjboy** [DefinitelyTyped/tsd#232]
i want to use tsd.but when i use tsd query node in cmd show these error : 
[ERR!] cwd  : D:\pdf-app
[ERR!] os   : Windows_NT 6.3.9600
[ERR!] argv : "D:\\PROGRAM FILES\\NODEJS\\node.exe" "C:\\Users\\wujiajun\\AppData\\Roaming\\npm\\node_modules\\tsd\\build\\cli.js" "query" "node"
[ERR!] node : v4.2.0
[ERR!] tsd  : 0.6.5
[ERR!] Error: connect ETIMEDOUT 204.13.251.16:443
[ERR!] CODE : ETIMEDOUT
[ERR!] connect ETIMEDOUT 204.13.251.16:443
This is most likely not a problem with tsd itself
and is related to network connectivity.
In most cases you are behind a proxy or have bad network settings.

If you are behind a proxy, please make sure that the
'proxy' config is set properly.  See: https://github.com/DefinitelyTyped/tsd#tsdrc
[ERR!] 
Error: connect ETIMEDOUT 204.13.251.16:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

[ERR!] tsd.json: {"version":"v4","repo":"borisyankov/DefinitelyTyped","ref":"master","path":"typings","bundle":"typings/tsd.d.ts","installed":{}}

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    D:\pdf-app\tsd-debug.log

and this is the settings
D:\pdf-app>tsd settings
{
   "version": "tsd 0.6.5",
   "repo": "https://github.com/borisyankov/DefinitelyTyped #master",
   "paths": {
      "startCwd": "D:\\pdf-app",
      "configFile": "D:\\pdf-app\\tsd.json",
      "cacheDir": "C:\\Users\\wujiajun\\AppData\\Roaming\\tsd-cache"
   },
   "typings": "D:\\pdf-app\\typings",
   "config": {
      "version": "v4",
      "repo": "borisyankov/DefinitelyTyped",
      "ref": "master",
      "path": "typings",
      "bundle": "typings/tsd.d.ts",
      "installed": {}
   }
}
please tell me how to use it.

**Comment by wjjboy** [comment]
it is the hosts problem.i have resolve it.

**Comment by niels-m** [comment]
how do you resolve it?
