### ISSUE TITLE
Update the tsd.json's repo default

### ISSUE THREAD

**Issue by radek-holy** [DefinitelyTyped/tsd#242]
IIUIC, the repository `borisyankov/DefinitelyTyped` is now `DefinitelyTyped/DefinitelyTyped`. I guess that it's a good idea to update the documentation and the `tsd init` command (and maybe also the hardcoded default value if it does not break compatibility) with regard to the value of the `repo` property.

BTW, can you please tell me when the repository have been transferred? Or at least whether it happened before 2015-10-01?

**Comment by blakeembrey** [comment]
@radek-holy No, the change was more recent than that. It happened about 8 days ago now. Yes, old links should definitely be updated now.

**Comment by radek-holy** [comment]
Ah, OK, then it was a bit premature to file this... :) Thanks for the info.
