### ISSUE TITLE
tsd does not update 'tsd.json' if it is executed via npm script

### ISSUE THREAD

**Issue by balazs4** [DefinitelyTyped/tsd#244]
I defined the following 'shortcut' in the `package.json`:
````json
"scripts": {
    "tsd": "tsd",
    "test": "gulp test"
  },
````

If I wanted to execute the following command:
`npm run tsd install mocha --save`
the typedef of mocha will be downloaded but the `installed` object in the `tsd.json` remains empty.
````json
"installed": {}
````

If the `tsd` is installed globally and I execute the same command (without `npm run` of course) it works as expected. Typedefinition of the package is in the typings folder and the `tsd.json` is up-to-date.

`tsd install mocha --save`

````json
"installed": {
    "mocha/mocha.d.ts": {
      "commit": "efd40e67ff323f7147651bdbef03c03ead7b1675"
    }
  }
````

I think it would be very useful if the `tsd` could be executed with the `npm run`

**Comment by bradacina** [comment]
+1

**Comment by janslow** [comment]
You need to use `npm run tsd -- install mocha --save`.

The [NPM run-script command](https://docs.npmjs.com/cli/run-script) requires you to put a `--` between the script name (and NPM args) and the script args.

**Comment by blakeembrey** [comment]
Closing this as resolved. Please follow @janslow's comment to use arguments with an NPM script.
