### ISSUE TITLE
angular material $mdDialog.show(fullscreen: true)

### ISSUE THREAD

**Issue by gabrielmuresan** [DefinitelyTyped/tsd#248]
Angular material $mdDialog has the fullscreen option that TSD definition does not implement.

```
$mdDialog.show({
      controller: DialogController,
      templateUrl: 'dialog1.tmpl.html',
      parent: angular.element(document.body),
      targetEvent: ev,
      clickOutsideToClose:true,
      fullscreen: $mdMedia('sm') && $scope.customFullscreen
    })
```

from the JS tab 
https://material.angularjs.org/latest/demo/dialog

**Comment by blakeembrey** [comment]
I think you've got the wrong repo. Try opening it up over at https://github.com/DefinitelyTyped/DefinitelyTyped, which holds all the type definitions.
