### ISSUE TITLE
tsd init Error: Use of const in strict mode in JOI module files

### ISSUE THREAD

**Issue by clhoultby** [DefinitelyTyped/tsd#250]
Hello, 

This is my first time trying to set up a typescript app via node and I can't get the typings folder & files installed. 

Trying to run a tsd init on a new Visual Studio project and keep receiving errors on the .js files in joi modules.

e.g. in the ...users/AppData/Roaming/npm/node_modules/tsd/node_modules/joi/lib folder.

Can someone advise?

my npm version is: 1.3.2
my tsd vesion is : 0.6.5

I've attached a screenshot of my cmd line error.

My package.json looks like:

{
  "name": "dietapp"
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "gulp": "~3.9.0",
    "gulp-debug": "^2.0.1",
    "gulp-inject": "^1.2.0",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-tslint": "^1.4.4",
    "gulp-typescript": "~2.10.0",
    "gulp-rimraf": "^0.1.1",
    "gulp-tsd": "0.0.4"
  },
  "author": "",
  "license": "BSD",
  "dependencies": {
    "typescript": "~1.7.3"
  }
}

![image](https://cloud.githubusercontent.com/assets/13684171/11610357/7e435212-9b98-11e5-8886-2bbd8c1560e7.png)

**Comment by blakeembrey** [comment]
Can you upgrade to at least node 0.12 at all?

**Comment by clhoultby** [comment]
I've updated to the latest version, had to go round the houses and update everything and reinstall the joi module, but I've got it working.

Thank yo very much!

**Comment by blakeembrey** [comment]
Glad to hear, thanks for the update! :smile:
