### ISSUE TITLE
error TS2300: Duplicate identifier

### ISSUE THREAD

**Issue by DimaSol** [DefinitelyTyped/tsd#252]
Hi,
I'm building an app using angular2 and using tsd for some typeScript libs.
angular2 is being installed using npm and I'm importing the oboe package with tsd.
When doing so, I'm getting an error of duplicated identifier for each and every node identifier because tsd is loading node as oboe dependency while angular2 has all it dependent *.d.ts in it sources (node.d.ts is one of them).
Is there a proper way to overcome it? I don't sure if this is a bug or not.

**Comment by blakeembrey** [comment]
This is a core issue of the current packing strategy of DefinitelyTyped, but it should be solved in Angular. Feel free to contribute to the issues over there. See https://github.com/angular/angular/issues/5807, https://github.com/angular/angular/issues/5459 and https://github.com/angular/angular/issues/5395.
