### ISSUE TITLE
Add component function to angular.d.ts

### ISSUE THREAD

**Issue by jusefb** [DefinitelyTyped/tsd#255]
Hi,

I would like to use the component function within angular js this function is coming in the 1.5 version of angular but can be used with older versions of angular via this plugin https://github.com/toddmotto/angular-component. How would I go about adding this to the type definition? Is there a way to extend the type definition without changing the existing one? Or how can I add the definition for this function into the angular.d.ts file?

Kind regards

Jusef

**Comment by blakeembrey** [comment]
You should contribute your type definition over at https://github.com/DefinitelyTyped/DefinitelyTyped. They'll be be able to give you the best answers too, but just creating a `angular-component/angular-component.d.ts` definition should be ok. You can also improve `angular/angular.d.ts` in the DefinitelyTyped repo too. If it's coming in 1.5, you should be good to improve it.

**Comment by jusefb** [comment]
Ok, thanks I will give that a go
