### ISSUE TITLE
ogle analytics

### ISSUE THREAD

**Issue by pillowsoft** [DefinitelyTyped/tsd#256]

**Comment by blakeembrey** [comment]
If this is a definition request, please open at https://github.com/DefinitelyTyped/DefinitelyTyped. Also, consider providing more detail than "ogle request".

**Comment by pillowsoft** [comment]
My bad, sorry!!!!  Was typing in another window must have accidentally hit enter on this.

**Comment by blakeembrey** [comment]
No worries, I could guess what you meant anyway :wink: But yeah, wrong repo. Try opening it in DefinitelyTyped.
