### ISSUE TITLE
Duplicate definitions from bower and npm

### ISSUE THREAD

**Issue by Draccoz** [DefinitelyTyped/tsd#270]
Hello everyone. I have a project based on bower, where I am using Immutable library. I am also using BrowserSync to develop. The problem I'm having is that BrowserSync also uses Immutable, but the npm based one, so when I do the `tsd link`, I get both npm and bower version in the tsd.d.ts, which then causes `Duplicate identifier` errors.
Can it be done somehow to include only modules declared in package.json? I do not want to manually remove that as we try to automate everything.
Thanks,
Daniel

**Comment by blakeembrey** [comment]
See https://github.com/DefinitelyTyped/tsd/issues/269, https://github.com/DefinitelyTyped/tsd/issues/150 and https://github.com/DefinitelyTyped/tsd/issues/234 where the issue is discussed.
