### ISSUE TITLE
tsd query angular2 returns zero results

### ISSUE THREAD

**Issue by siulm** [DefinitelyTyped/tsd#273]
Running 
tsd install angular2 es6-promise rx rx-lite

installs es6-promise rs and rx-lite but not angular2

running:
tsd install angular2  or  tsd query angular2 --save --action install --resolve
returns zero results.

can you help?

**Comment by blakeembrey** [comment]
Angular 2 typings are provided as part of the NPM module, why do you need to install them with TSD?

**Comment by rodrigoEclipsa** [comment]
There are currently no angular2.d.ts in node_modules / angular2 / typings

**Comment by siulm** [comment]
Thanks. I did not know that at the time I sent you the message. But did my
leg work and I learn it. Thanks for taking your time.

**Comment by dawidk92** [comment]
+1

**Comment by dawidk92** [comment]
@siulm have you resolved this somehow?

**Comment by siulm** [comment]
David hi.  Yes.

Blake said: Angular 2 typings are provided as part of the NPM module.

He was right.  I found it on line and Blake was nice to confirm it.
Once you install Angular2 with npm, The problem goes away.  All the tsd is
part of the node modules

I hope this helps

Luis

**Comment by RajenRanjith** [comment]
Yes,

Still i face the same problem like: 

src/app/app.ts(1,36): error TS2307: Cannot find module 'angular2/angular2'.
5:47:02 PM - Compilation complete. Watching for file changes.

How to solve this, anyone please help me..

**Comment by KapuzenSohn** [comment]
Try this in your bootstrap file:
`///<reference path="../node_modules/angular2/typings/browser.d.ts"/>`

I think it was in a recent update that they changed something with the typings

**Comment by siulm** [comment]
If I am not mistaken, it should be angular2/core instead of
angular2/angular2.

Hope that helps.

**Comment by vinothbabu** [comment]
`tsd query angular2/core` also returns zero results...

**Comment by siulm** [comment]
Have done a 'npm install angular2'

That should install all requirements for angular 2.  Typings will be part
of it

**Comment by Jenan** [comment]
I don't find angular2.d.ts as part of package via NPM. 

Is exists any solution for this issue?
Thanks.

**Comment by lentebloem** [comment]
I installed tsd via npm, yet angular2 is still not found. Does anyone know how to solve this issue?
Thank you!

**Comment by blakeembrey** [comment]
See https://github.com/DefinitelyTyped/tsd/issues/273#issuecomment-181607758
