### ISSUE TITLE
Github limit reached

### ISSUE THREAD

**Issue by boghy8823** [DefinitelyTyped/tsd#279]
I'm trying to install lodash using tsd but I get this error: 
"[ERR!] GitHub API: GitHub rate limit reached.
    To increase the limit use GitHub authentication.
    See: https://github.com/DefinitelyTyped/tsd#tsdrc"

![tsd_lodash](https://cloud.githubusercontent.com/assets/4687998/13524534/0fbd0126-e1fc-11e5-8cf4-16bf72a61d8f.png)

**Comment by blakeembrey** [comment]
Did you look at https://github.com/DefinitelyTyped/tsd#tsdrc? You can specify the GitHub token to have a larger request rate (by default, you can only make 50 API requests per hour).

**Comment by boghy8823** [comment]
Yes, it worked. Thanks!
