### ISSUE TITLE
empty definition for backbone

### ISSUE THREAD

**Issue by vermokhin** [DefinitelyTyped/tsd#285]
HI! I tried to use backbone definition with command 'typings install backbone --ambient --save' but the defiinition file doesn't contains any definition information.
Attached file is index.d.ts from typings/ambient/*/backbone directory. Files for main and desktop version are same.
[index.txt](https://github.com/DefinitelyTyped/tsd/files/233127/index.txt)

**Comment by Diullei** [comment]
Hi @vermokhin! you need to open an issue at typings repository. https://github.com/typings/typings/issues
