### ISSUE TITLE
Is it possible to contribute to a DefinetelyTyped Library through tsd?

### ISSUE THREAD

**Issue by marcoarruda** [DefinitelyTyped/tsd#288]
I am using tsd to use a library in a project.
But, I'd like to contribute to this library definition.
Is there a way to commit changes to a library definition file through tsd tool?

Thanks!

**Comment by Diullei** [comment]
Hi @marcoarruda, you can't make changes through tsd tool. You will need to send a PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) if you want to contribute to any definition. Please see the contribution guide http://definitelytyped.org/guides/contributing.html
