### ISSUE TITLE
tsd reinstall does not generate tsd.d.ts

### ISSUE THREAD

**Issue by nathggns** [DefinitelyTyped/tsd#80]
I don't like having any of my generated files in source control, so I think it would be desirable for `tsd reinstall` to generate the `tsd.d.ts` file that is created when installing references. 

I'll have a look at creating a pull request for this.

**Comment by chaosmail** [comment]
Maybe a simple `tsd install` could install everything (`typings/` and `tsd.d.ts`) from the `tsd.json` file. just saying..
