### ISSUE TITLE
npm install fails due to dependency not found

### ISSUE THREAD

**Issue by kostaad** [DefinitelyTyped/tsd#84]
Hi tried, to install with npm install  and got this:
npm ERR! git fetch -a origin (git://github.com/Bartvds/update-notifier/) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/Bartvds/update-notifier/) github.com[0: 192.30.252.129]: errno=No such file or directory
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=No such file or directory
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "grunt-tsd" "-g"
npm ERR! cwd C:\dev\iandmine\Source\Client
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     C:\dev\iandmine\Source\Client\npm-debug.log
npm ERR! not ok code 0

**Comment by ahmedsayedig** [comment]
Thanks Bartvds!

The fix that worked for me is:
git config --global url."https://".insteadOf git://

**Comment by fredericksilva** [comment]
Thanks @Bartvds !!

**Comment by tzawadzki** [comment]
Thx @Bartvds it works !

**Comment by nateshmbhat** [comment]
Actually I was stuck with the same problem . Here's how I fixed it .

- I found that the problem for me was having an older version of npm which was causing this issue. 
- I uninstalled it using `sudo apt-get remove npm` and installed it again using `sudo apt-get install npm` .
- Then upgrade it to the latest version using `sudo npm install npm@latest -g`
