### ISSUE TITLE
tsd not recognized as command on Windows

### ISSUE THREAD

**Issue by bcardi** [DefinitelyTyped/tsd#88]
I am running Windows 8 and I've installed tsd as follows

npm install -g tsd

When I try to run tsd from the command line I get the following error

'tsd' is not recognized as an internal or external command, operable program or batch file.

When I look in my root npm folder, I do not see a "tsd.cmd" file, which is required for Windows.

**Comment by pranaydutta89** [comment]
not working for me too ,please provide me with a solution

**Comment by hichetan** [comment]
I know its been while you closed this ticket. I tried all above given solutions and they are not working for me. Please help.
